###
GET http://localhost:8080/Floor/AlcoholicDrinks

###
GET http://localhost:8080/Floor/Appetizers

###
GET http://localhost:8080/Floor/Desserts

###
GET http://localhost:8080/Floor/Entrees

###
GET http://localhost:8080/Floor/NonAlcoholicDrinks

###
GET http://localhost:8080/Floor/Sides

###
GET http://localhost:8080/Tickets/OpenTickets

###
POST http://localhost:8080/Tickets/newTicket
Content-Type: application/json

###
GET http://localhost:8080/Management/retrieveAllEmployees

###
POST http://localhost:8080/Management/addNewEmployee
Content-Type: application/json

{
    "firstName": "Jerry",
    "lastName": "Wilder",
    "jobTitle": "Manager"
}

### 
GET http://localhost:8080/Management/retrieveCompanyProfile/1


/// broken ///
###
PATCH http://localhost:8080/Management/changeTaxRate/1 
Content-Type: application/json

{
    "companyName": "Brew’d Awakening",
    "companyAddress": "1609 Bad Route rd, Beach front city, fl 37099",
    "taxRate": "0.08"
}