###
GET http://localhost:8080/Floor/AlcoholicDrinks

###
GET http://localhost:8080/Floor/Appetizers

###
GET http://localhost:8080/Floor/Desserts

###
GET http://localhost:8080/Floor/Entrees

###
GET http://localhost:8080/Floor/NonAlcoholicDrinks

###
GET http://localhost:8080/Floor/Sides

###
GET http://localhost:8080/Tickets/OpenTickets

###
POST http://localhost:8080/Tickets/newTicket
Content-Type: application/json

{

}


###
GET http://localhost:8080/Management/retrieveAllEmployees

###
POST http://localhost:8080/Management/addNewEmployee
Content-Type: application/json

{
    "firstName": "Jerry",
    "lastName": "Wilder",
    "jobTitle": "Manager"
}

### 
GET http://localhost:8080/Management/retrieveCompanyProfile/1


/// broken ///
###
PATCH http://localhost:8080/Management/changeTaxRate/1 
Content-Type: application/json

0.07

###
PATCH http://localhost:8080/Tickets/28/addItem/entree
Content-Type: application/json

  {
    "name": "Cheese Burger",
    "price": 8.99,
    "description": "Classic american cheese burger served with lettuce, tomato, pickle, onion, mayo, and a side of fries",
    "available": true

  }

###
PATCH http://localhost:8080/Tickets/saveTicket/28
Content-Type: application/json

{
  "ticketItems": [
    {
    "name": "Budweiser",
    "price": 2.99,
    "isAlcoholic": true
    }
  ]
}

###
GET http://localhost:8080/Tickets/27

###
PATCH http://localhost:8080/Tickets/28/addItem/dessert
Content-Type: application/json

{
  "name": "Apple Pie",
  "price": 6.0,
  "showOnMenu": true,
  "description": "One piece of made in house Apple pie",
  "available": true
}

###
GET http://localhost:8080/Tickets/27/getTicketItems/

###
Put http://localhost:8080/Tickets/42/removeTicketItem/46

###
GET http://localhost:8080/Tickets/retireveAllKitchenTickets

###
DELETE http://localhost:8080/Tickets/27/finishTicket
